name: tech_world
description: Adventures In Tech World, for fun and profit.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  a_star_algorithm:
  flame: 1.0.0-releasecandidate.16
  vector_math: 
  ws_game_server_types:
    path: ../ws_game_server_types
  web_socket_channel:
  
  #######################
  # redfire dependencies
  #######################
  freezed_annotation:
  json_annotation: ^4.4.0
  redfire:
    path: ../redfire
  redux:
  flutter_redux:
  fast_immutable_collections:
  url_launcher: ^6.0.12
  flutter_markdown: ^0.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  redfire_lints:
    path: ../redfire_lints
  redfire_test:
    path: ../redfire_test
  build_runner:
  freezed:
  json_serializable: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/bald.png
    - assets/images/beard.png