name: redaux_widgets_test_utils
description: Helper classes for testing apps that use redaux_widgets.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  redaux:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/redaux
  redaux_widgets:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/redaux_widgets
  json_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_types

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
