name: astro_auth
description: Drop-in astro components for authentication.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.4.0
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  astro_locator:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/astro_locator
  astro:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro
  astro_navigation:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_navigation
  astro_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_types

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
  astro_test_utils:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_test_utils
