name: astro_auth
description: Drop-in astro components for authentication.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.4.0
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  locator:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/locator
  astro:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro
  astro_state_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/interfaces/astro_state_interface
  json_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_types

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
  astro_test_utils:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_test_utils
