name: flutter_box2d
description: A flutter plugin for Box2D - a 2D Physics Engine for Games.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_box2d_platform_interface:
    path: ../flutter_box2d_platform_interface
  flutter_box2d_web:
    path: ../flutter_box2d_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        default_package: flutter_box2d_web
