name: process_articles_in_emails
description: A Dart microservice that processes & saves articles in emails.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  firestore_api_client:
    path: ../api-clients/firestore_api_client
  json_utils:
    path: ../json_utils
  shelf: ^1.1.0

dev_dependencies:
  http: ^0.13.4
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
