name: gather_link_account_shelf
description: A server app using the shelf package and Docker.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  firestore_api_client:
    path: ../../api-clients/firestore
  json_utils:
    path: ../../utils/json_utils
  googleapis_auth: ^1.3.1
      

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
