name: gather_link_account_shelf
description: A server app using the shelf package and Docker.
version: 0.0.0-a1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.0.0
  firebase_admin:
    git:
      url: https://github.com/nickmeinhold/firebase_admin
      ref: add-adc
  googleapis_auth: ^1.3.1
  http: ^0.13.4
  json_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_types
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0