name: firestore_api_client
description: Convenience wrappers around the googleapis.dart Firestore API.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  firestore_service_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/interfaces/firestore_service_interface
    # path: ../../../../interfaces/firestore_service_interface
  googleapis_utils:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/googleapis_utils
    # path: ../../utils/googleapis_utils

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
