name: flireator
description: A project creation tool for Flutter projects with a Firebase
  backend, stored on GitHub.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redfire:
    path: ../redfire
  freezed_annotation:
  json_annotation:
  redux:
  flutter_redux:
  fast_immutable_collections:

  url_launcher: any
  oauth2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  redfire_test:
    path: ../redfire_test
  build_runner:
  freezed:
  json_serializable:
  test: any
  mockito: any

flutter:
  uses-material-design: true