name: firebase_auth_service_interface
description: An interface for a firebase auth service.
version: 0.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  astro_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_types

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
