name: firebase_auth_service_interface
description: An interface for a firebase auth service.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
