include: package:lints/recommended.yaml

# Weening off pedantic.
linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last # (included in package:flutter_lints)
    - unawaited_futures

analyzer:
#   exclude:
#     - path/to/excluded/files/**
