name: the_process
description: A tool to automate "the process".

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependency_overrides:
  crypto: ^3.0.0-nullsafety.0
  firebase_core: ^0.8.0-nullsafety.1
  firebase_core_platform_interface: ^4.0.0-nullsafety.0
  firebase_core_web: ^0.3.0-nullsafety.0
  quiver: ^3.0.0-nullsafety.2
  plugin_platform_interface: ^1.1.0-nullsafety.2

dependencies:
  flutter:
    sdk: flutter

  # auth
  firebase_auth: ^0.21.0-nullsafety.0
  google_sign_in: ^5.0.0-nullsafety
  sign_in_with_apple: ^3.0.0-nullsafety.0

  # built_value
  built_collection: 5.0.0-nullsafety.0
  built_value: 8.0.0-nullsafety.0
  
  # database
  cloud_firestore: ^0.17.0-1.0.nullsafety.0

  # firebase 
  firebase_core: ^0.8.0-nullsafety.1

  # messaging 
  firebase_messaging: ^9.0.0-1.0.nullsafety.0

  # platform 
  url_launcher: ^6.0.0-nullsafety.1

  # redux
  redux:
  flutter_redux:
  redux_remote_devtools:

  # utils 
  uuid: ^3.0.0-nullsafety.0

dev_dependencies:
  integration_test:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  mockito: ^5.0.0-nullsafety.1
  
  build_runner: ^1.0.0
  built_value_generator: 8.0.0-nullsafety.0

flutter:
  uses-material-design: true
  assets:
    - assets/
