name: adventures_in_tech_world
description: Assisting learning and collaboration.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio:
  firebase_core:
  
  # auth 
  oauth2:
  firebase_auth:
  google_sign_in:
  sign_in_with_apple:

  # database 
  cloud_firestore:

  # github graphql client
  github_graphql_client:
    git: https://github.com/Adventures-In/github_graphql_client.git

  # platform tools 
  url_launcher:
  shared_preferences:

  # redux 
  built_value:
  built_collection:
  redux:
  flutter_redux:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner:
  built_value_generator:
  redux_remote_devtools:
  pedantic:
  test:
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
   - family:  OctoIcons
     fonts:
      - asset: fonts/OctoIcons.ttf