name: the_process
description: A tool to automate "the process".

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

# dependency_overrides:
#   analyzer: '0.41.0'

# Dependency overrides are needed to use null safe `built_value` until it rolls
# into `package:build_runner`.
dependency_overrides:
  built_collection: 5.0.0-nullsafety.0
  built_value: 8.0.0-nullsafety.0

dependencies:
  flutter:
    sdk: flutter

  # auth
  firebase_auth:
  google_sign_in:
  sign_in_with_apple: ^3.0.0-nullsafety.0

  # built_value
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2
  
  # database
  cloud_firestore:

  # firebase 
  firebase_core:

  # messaging 
  firebase_messaging:

  # platform 
  url_launcher: ^6.0.0-nullsafety.1

  # redux
  redux:
  flutter_redux:
  redux_remote_devtools:

  # utils 
  uuid:

dev_dependencies:
  integration_test:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  mockito: ^5.0.0-nullsafety.1
  
  build_runner: ^1.0.0
  built_value_generator:
    git:
      url: git@github.com:google/built_value.dart.git
      path: built_value_generator

flutter:
  uses-material-design: true
  assets:
    - assets/
