name: redfire
description: A Redux based architecture connected to Firebase streams.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: any
  # auth
  firebase_auth: any
  google_sign_in: any
  sign_in_with_apple: any 
  # database
  cloud_firestore: any
  # platform 
  url_launcher: any

  redux: any
  flutter_redux: any
  fast_immutable_collections: any
  freezed_annotation: any
  json_annotation: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: any
  freezed: any
  json_serializable: any
  test: any
  mockito: any
  redfire_test:
    git: https://github.com/enspyrco/redfire_test.git
    # path: /Users/nick/git/orgs/enspyrco/redfire_test

flutter:
  assets:
    - packages/redfire/assets/apple_white.png
    - packages/redfire/assets/google.png
    - packages/redfire/assets/github.png
