name: tech_world_server
description: Using shelf_web_socket with functions_framework for a serverless websocket server.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.0.0
  shelf_web_socket: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.4
  functions_framework_builder: ^0.4.2
  test: ^1.15.7
  test_process: ^2.0.0
