name: adventures_in_tech_world
description: Assisting learning and collaboration.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # auth 
  oauth2:
  firebase_auth:

  # database 
  cloud_firestore:

  # platform tools 
  url_launcher:
  shared_preferences:

  # redux 
  built_value:
  built_collection:
  redux:
  flutter_redux:

  # used in prototyping, will not be in release 
  redux_remote_devtools:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:
  pedantic:
  test:
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/GitHub-Mark-Light-64px.png