name: tech_world
description: Adventures In Tech World, for fun and profit.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  a_star_algorithm:
  flame: ^1.0.0-releasecandidate.13
  web_socket_game_server_types:
    git: https://github.com/Adventures-In/web_socket_game_server_types.git
  web_socket_channel:
  
  #######################
  # redfire dependencies
  #######################
  freezed_annotation:
  json_annotation:
  redfire:
    # git: https://github.com/enspyrco/redfire.git
    path: /Users/nick/git/orgs/enspyrco/redfire
  redux:
  flutter_redux:
  fast_immutable_collections:

dev_dependencies:
  flutter_test:
    sdk: flutter
  redfire_test:
    # git: https://github.com/enspyrco/redfire_test.git
    path: /Users/nick/git/orgs/enspyrco/redfire_test
  flutter_lints:
  build_runner:
  freezed:
  json_serializable:

flutter:
  assets:
    - assets/images/bald.png