name: tech_world
description: Adventures In Tech World, for fun and profit.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  a_star_algorithm:
  flame: ^1.0.0-releasecandidate.13
  vector_math: 
  ws_game_server_types:
    git: 
      url: https://github.com/adventures-in/ws_game_server_repo.git
      path: ws_game_server_types
    # path: /Users/nick/git/orgs/adventures_in/microservices/ws_game_server_repo/ws_game_server_types
  web_socket_channel:
  
  #######################
  # redfire dependencies
  #######################
  freezed_annotation:
  json_annotation:
  redfire:
    git: 
      url: https://github.com/enspyrco/redfire.git
      path: redfire
    # path: /Users/nick/git/orgs/enspyrco/redfire/redfire
  redux:
  flutter_redux:
  fast_immutable_collections:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  redfire_test:
    git: 
      url: https://github.com/enspyrco/redfire.git
      path: redfire_test
    # path: /Users/nick/git/orgs/enspyrco/redfire/redfire_test
  flutter_lints:
  build_runner:
  freezed:
  json_serializable:

flutter:
  assets:
    - assets/images/bald.png
    - assets/images/beard.png