name: shared_models
description: A package for sharing models between the_process files and dart_microservices files.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_serializable: any
  freezed_annotation: any
  googleapis: any

dev_dependencies:
  build_runner: any
  freezed: any
  pedantic: any