name: discord_api_client
description: An API Client for Discord, written in Dart.
version: 0.0.1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
