name: tech_world
description: Adventures In Tech World, for fun and profit.
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  a_star_algorithm:
  flame: 1.0.0-releasecandidate.16
  vector_math: 
  ws_game_server_types:
    path: ../../../../dart/servers/ws_game_server_types
  web_socket_channel:
  
  #######################
  # redfire dependencies
  #######################
  freezed_annotation:
  json_annotation: ^4.5.0
  redfire:
    path: ../../../../flutter/utils/redfire
  firestore_service_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/interfaces/firestore_service_interface
  redux:
  flutter_redux:
  fast_immutable_collections:
  url_launcher: ^6.0.12
  flutter_markdown: ^0.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  redfire_lints:
    path: ../../../../flutter/utils/redfire_lints
  redfire_test:
    path: ../../../../flutter/utils/redfire_test
  build_runner:
  freezed:
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bald.png
    - assets/images/beard.png