name: git_vis
description: A Flutter app to visualise the git commit history with a delightful UI for performing git commands.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1

  # astro
  astro:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro
  astro_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_types
  astro_locator:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/astro_locator
  astro_inspector_screen:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_inspector_screen
  astro_error_handling:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_error_handling
  astro_navigation:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^7.2.2
  astro_test_utils:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_test_utils
  enspyr_lints:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/enspyr_lints

ffigen:
  output: "lib/git/native_bindings/libgit2_bindings.dart"
  headers:
    entry-points:
      - "native/libgit2/include/*.h"
      # - "native/libgit2/src/libgit2/refs.h"
  compiler-opts:
    - '-Wno-nullability-completeness'
    - '-Inative/libgit2/include'
  name: "LibGit2"
  description: "Bindings for libgit2"