name: curator
description: A Dart microservice that curates articles in emails.
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  # args: ^2.0.0
  gcloud: ^0.8.5
  shelf: ^1.1.0

dev_dependencies:
  http: ^0.13.4
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
