name: authorization_code_flow
description: A server app using the shelf package and Docker.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0-116.0.dev <3.0.0'


dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
