name: notion_pages_to_web_tutorial
description: Dart microservice to convert Notion pages to web tutorials with Flutter.
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  shelf: ^1.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
