name: github_api_envoy
description: A server app that receives authenticated requests and interacts with the GitHub API via a GitHub App.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  corsac_jwt: ^1.0.0-nullsafety.1
  googleapis: ^8.0.0
  googleapis_auth: ^1.3.0
  http: ^0.13.4
  shelf: ^1.1.0
  secret_manager_api_client:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/api-clients/secret_manager_api_client
      ref: github-app-auth
    # path: ../api-clients/secret_manager_api_client
  git_hub_api_client:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/api-clients/git_hub_api_client
      ref: github-app-auth
    # path: ../api-clients/git_hub_api_client

dev_dependencies:
  lints: ^1.0.0
  test: ^1.15.0
