name: run_dart_code_in_pubsub_message
description: A microservice that runs Dart code received in a Pub/Sub message.
version: 0.0.0-a1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  googleapis: ^10.1.0
  http: ^0.13.5
  shelf: ^1.4.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
