name: astro_navigation
description: The default astro navigation plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  astro_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_types
  astro:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro
  astro_locator:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/astro_locator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
