name: redaux_widgets
description: Widgets for interacting with a redux store from enspyr_redux.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  redaux:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/redaux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
