name: api_client_utils
description: Classes for use in API Clients.
version: 0.0.0-a1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
