name: discord_interaction_to_pubsub_message
description: A microservice that turns Discord Interactions into PubSub messages.
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  gcloud: ^0.8.5
  shelf: ^1.2.0
  convert: ^3.0.1
  ed25519_edwards: ^0.3.1
  googleapis_auth: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  http: ^0.13.4