// The bindings generated by emscripten use this function "array_bounds_check" which 
// calls back into JS via "array_bounds_check_error".
//
// For now I have removed the call into the JS function, disabling the bounds check,
// and will come back and look into what we need to do in the case of Dart/C++ bindings

// // Not using size_t for array indices as the values used by the javascript code are signed.
// EM_JS(void, array_bounds_check_error, (size_t idx, size_t size), {
//   throw 'Array index ' + idx + ' out of bounds: [0,' + size + ')';
// });

void array_bounds_check(const int array_size, const int array_idx) {
  if (array_idx < 0 || array_idx >= array_size) {
    // array_bounds_check_error(array_idx, array_size);
  }
}