name: create_section
description: A microservice for creating sections in TheProcess, made with Dart Functions Framework.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependency_overrides:
  # In order to use null-safe freezed, version solving needed to have functions_framework migrated and importing null-safe json_annotation
  functions_framework:
    git:
      url: https://github.com/nickmeinhold/functions-framework-dart
      path: functions_framework
      ref: null-safe

dependencies:
  functions_framework: any
  shelf: ^1.0.0-nullsafety.0
  http: ^0.13.0-nullsafety.0
  json_serializable: ^4.0.0-nullsafety.0
  freezed_annotation: ^0.13.0-nullsafety.0
  googleapis: any
  googleapis_auth: ^1.0.0-nullsafety.0
  shared_models:
    git:
      url: https://github.com/enspyrco/the_process
      path: shared_models

dev_dependencies:
  build_runner: any
  build_verify: any
  functions_framework_builder:
    # We need the builder to add // @dart=2.9 to server.dart for no-sound-null-safety
    git:
      url: https://github.com/nickmeinhold/functions-framework-dart
      path: functions_framework_builder
      ref: null-safe
  test: ^1.16.0-nullsafety.16
  test_process: any
  mockito: ^5.0.0-nullsafety.7