name: create_section
description: A microservice for creating sections in TheProcess, made with Dart Functions Framework.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functions_framework: any
  shelf: any
  http: any
  json_serializable: any
  freezed_annotation: any
  googleapis: any
  googleapis_auth: any
  shared_models:
    git:
      url: https://github.com/enspyrco/the_process
      path: shared_models

dev_dependencies:
  build_runner: any
  build_verify: any
  functions_framework_builder: any
  test: any
  test_process: any
  mockito: any