name: firestore_service_interface
description: A common interface for firestore services built on googleapis & cloud_firstore.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_utils:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_utils

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
