name: enspyr_lints
description: Recommended lints for Enspyr apps.
repository: https://github.com/enspyrco/monorepo/tree/main/packages/enspyr_lints
issue_tracker: https://github.com/enspyrco/monorepo/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+enspyr_lints%22
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter_lints: ^2.0.1
