name: web_socket_game_server
description: Using shelf_web_socket with functions_framework for a serverless websocket game server.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  functions_framework:
  googleapis:
  googleapis_auth:
  shelf:
  shelf_web_socket:
  web_socket_channel:
  fast_immutable_collections:
  web_socket_game_server_types:
    path: ../web_socket_game_server_types

dev_dependencies:
  build_runner:
  functions_framework_builder:
  lints:
  test:
  test_process:
