name: process_articles_in_emails
description: A Dart microservice that processes & saves articles in emails.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  firestore_service_googleapis:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/api-clients/firestore/firestore_service_googleapis
  json_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_types
  shelf: ^1.1.0

dev_dependencies:
  http: ^0.13.4
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
