include: package:enspyr_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - build/**
    - lib/*.g.dart
    - lib/*.freezed.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/**/*.mocks.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true