name: git_hub_api_client
description: A wrapper and convenience methods around the http package for accessing the GitHub API.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  corsac_jwt: ^1.0.0-nullsafety.1
  googleapis_auth: ^1.3.0
  http: ^0.13.4
  json_utils:
    path: ../../json_utils
  
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
