name: run_dart_code_in_pubsub_message
description: A microservice that runs Dart code received in a Pub/Sub message.
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  googleapis: ^7.0.0
  http: ^0.13.4
  shelf: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.15.0
