name: json_utils
description: Dart utilities for JSON serialisation & deserialisation.
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
