name: coding_challenge_verifier
description: A Dart microservice that verifies pull requests for coding challenges.
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  shelf:
  crypto:
  googleapis:
  googleapis_auth:

dev_dependencies:
  lints:
  test:
  mockito: 
