targets:
  $default:
    builders:
      astro_generators|annotations:
        enabled: true

builders:
  astro_generators:
    target: ":astro_generators"
    import: "package:astro_generators/astro_builder.dart"
    builder_factories: ["astroState"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
