name: eventfire
description: Wrappers around Firebase & GCP packages for use in an event sourcing architecture.
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
