name: flutter_box2d_platform_interface
description: A common platform interface for the flutter_box2d plugin.
repository: https://github.com/enspyrco/monorepo/tree/main/packages/flutter-plugins/flutter_box2d/flutter_box2d_platform_interface
issue_tracker: https://github.com/enspyrco/monorepo/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+flutter_box2d%22
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
