name: redfire_test
description: Utilities to simplify testing in apps that use redfire.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.12.0
  firebase_auth:
  google_sign_in:
  sign_in_with_apple: ^3.3.0 # 3.2.0 → 3.3.0 was a breaking change due to federation
  http:
  redux:
  mockito:
  freezed_annotation:
  json_annotation: ^4.4.0
  fast_immutable_collections:

  redfire:
    path: ../redfire
  redfire_lints:
    path: ../redfire_lints
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:
  json_serializable: