name: flutter_box2d
description: A flutter plugin for Box2D.
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        dartPluginClass: FlutterBox2dWeb
        fileName: flutter_box2d_web.dart
