name: adventure_maker
description: Create, organise & discover adventures taking place in tech-world.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  
  redfire:
    path: ../redfire
  freezed_annotation:
  json_annotation: ^4.4.0
  redux:
  flutter_redux:
  fast_immutable_collections:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:

  redfire_lints:
    path: ../redfire_lints
  redfire_test:
    path: ../redfire_test

  build_runner:
  freezed:
  json_serializable: 

flutter:
  uses-material-design: true
