name: adventure_maker
description: Create, organise & discover adventures taking place in tech-world.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=2.6.0-0.0.pre"

dependencies:
  flutter:
    sdk: flutter
  
  redfire:
    path: ../redfire
  freezed_annotation:
  json_annotation: ^4.3.0
  redux:
  flutter_redux:
  fast_immutable_collections:

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  test:
  mockito:

  redfire_test:
    path: ../redfire_test

  build_runner:
  freezed:
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
