name: domain_visualiser
description: Draw diagrams to visualise & generate your project domain.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  redfire:
    path: ../redfire
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  freezed_annotation:
  json_annotation: ^4.4.0
  redux:
  flutter_redux:
  fast_immutable_collections:

  # utils 
  uuid: any
  flutterfire_ui: ^0.3.2
  
dev_dependencies:
  redfire_test:
    path: ../redfire_test
  build_runner:
  freezed:
  json_serializable: ^6.0.1

  redfire_lints:
    path: ../redfire_lints

flutter:
  uses-material-design: true
