name: redfire_lints
description: Recommended lints for RedFire apps.
repository: https://github.com/enspyrco/monorepo/tree/main/packages/redfire_lints
issue_tracker: https://github.com/enspyrco/monorepo/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+redfire_lints%22
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter_lints: ^1.0.0
