name: ws_game_server_types
description: Types for game objects sent via a ws_game_server.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  freezed_annotation:
  json_annotation:
  fast_immutable_collections: 

dev_dependencies:
  lints:
  test:
  build_runner:
  freezed:
  json_serializable:
