name: firestore_service_grpc
description: A Dart service to interface with Google's Firestore.
version: 0.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  fixnum: ^1.0.1
  grpc: ^3.1.0
  protobuf: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
