name: astro_test_utils
description: Helper classes for testing apps that use astro.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  astro:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro
  astro_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_types
  astro_locator:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/astro_locator
  firestore_service_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/interfaces/firestore_service_interface
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
