name: adventure_maker
description: Create, organise & discover adventures taking place in tech-world.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  redfire:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/redfire
  firestore_service_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/interfaces/firestore_service_interface
  freezed_annotation:
  json_annotation: ^4.6.0
  redux:
  flutter_redux:
  fast_immutable_collections:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:

  redfire_lints:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/redfire_lints
  redfire_test:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/redfire_test

  build_runner:
  freezed:
  json_serializable: 

flutter:
  uses-material-design: true
