name: ws_game_server_types
description: Types for game objects sent via a ws_game_server.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  freezed_annotation:
  fast_immutable_collections:
  json_annotation: ^4.4.0

dev_dependencies:
  lints:
  test:
  build_runner:
  freezed: 
  json_serializable: 
