name: ffigen_test
description: Experimenting with ffigen on C++ glue created by emscripten.
version: 0.0.1

# As at 10 Apr '22 we need to be on Flutter beta channel to get ARM64 Dart
# in order for ffigen to work on M1 Mac
environment:
  sdk: '>=2.17.0-182.2.beta <3.0.0'

dependencies: 
  ffigen: ^4.1.3

ffigen:
  output: 'out.dart'
  llvm-path:
    - '/opt/homebrew/opt/llvm'
  headers:
    entry-points:
      - 'in.h'