// Relative import to be able to reuse the C sources.
// See the comment in ../{projectName}}.podspec for more information.
#include "../../src/flutter_box2c.c"

#include "../../src/box2c/src/aabb.c"
#include "../../src/box2c/src/allocate.c"
#include "../../src/box2c/src/array.c"
#include "../../src/box2c/src/block_allocator.c"
#include "../../src/box2c/src/body.c"
#include "../../src/box2c/src/broad_phase.c"
#include "../../src/box2c/src/contact.c"
#include "../../src/box2c/src/contact_solver.c"
#include "../../src/box2c/src/distance.c"
#include "../../src/box2c/src/dynamic_tree.c"
#include "../../src/box2c/src/geometry.c"
#include "../../src/box2c/src/hull.c"
#include "../../src/box2c/src/island.c"
#include "../../src/box2c/src/manifold.c"
#include "../../src/box2c/src/math.c"
#include "../../src/box2c/src/pool.c"
#include "../../src/box2c/src/shape.c"
#include "../../src/box2c/src/stack_allocator.c"
#include "../../src/box2c/src/timer.c"
#include "../../src/box2c/src/types.c"
#include "../../src/box2c/src/world.c"
