name: calculate_percentage
description: Calculate percentage of lines covered from coverage info.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  lcov_parser: ^0.1.2

dev_dependencies:
  lints: ^1.0.0
