name: astro_error_handling
description: An astro plugin for error handling.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  locator:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/locator
  astro:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/astro
  astro_widgets:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_widgets
  json_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_types

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
