targets:
  astro_generator:astro_generator:
    builders:
      astro_generator|astroBuilder:
        enabled: True

builders:
  astroBuilder:
    import: 'package:astro_generator/astro_generator.dart'
    builder_factories: ['astroBuilder']
    build_extensions:
      .dart:
        - .g.dart
    build_to: source
    auto_apply: root_package