name: astro_inspector_screen
description: A widget for visualising state changes in an app using redux.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  astro:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro
  astro_locator:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/astro_locator
  json_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_types
  astro_core_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/interfaces/astro_core_interface
  astro_state_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/interfaces/astro_state_interface
  astro_error_handling:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_error_handling

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.4
  astro_test_utils:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_test_utils
