name: firestore_service_flutterfire
description: FlutterFire implementation of our FirestoreService interface.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.0.2
  flutter:
    sdk: flutter
  
  json_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_types
  firestore_service_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/interfaces/firestore_service_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
