name: notion_api_client
description: A Dart client for the Notion API.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  html: ^0.15.2
  api_client_utils:
    path: ../api_client_utils

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
