name: redfire
description: A redux based state management & navigation solution, with prebuilt modules for Firebase features.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core:
  firebase_auth:
  google_sign_in:
  sign_in_with_apple: ^3.3.0 # 3.2.0 → 3.3.0 was a breaking change due to federation
  cloud_firestore:
  url_launcher:
  redux:
  flutter_redux:
  fast_immutable_collections:
  freezed_annotation:
  json_annotation: ^4.6.0
  flutterfire_ui: ^0.3.2
  firestore_service_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/interfaces/firestore_service_interface
  cloud_firestore_extensions:
    path: ../flutterfire/cloud_firestore_extensions
    # git:
    #   url: https://github.com/enspyrco/monorepo.git
    #   path: packages/flutter/utils/flutterfire/cloud_firestore_extensions
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:
  json_serializable:
  test:
  mockito:
  redfire_test:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/redfire_test
  redfire_lints:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/redfire_lints

flutter:  
  fonts:
    - family:  RedFireIcons
      fonts:
        - asset: packages/redfire/assets/RedFireIcons.ttf
        
  assets:
    - packages/redfire/assets/apple_white.png
    - packages/redfire/assets/google.png
    - packages/redfire/assets/github.png
