name: github_api_interactions
description: A server app that recieves authenticated requests and interacts with the GitHub API via a GitHub App.
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  corsac_jwt: ^0.4.0
  http: ^0.13.4
  shelf: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.15.0
