name: presinter
description: Flutter apps for interactive presentations.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutterfire_ui: ^0.3.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  redfire_lints:
    path: ../../../flutter-apps/utils/redfire_lints
  redfire_test:
    path: ../../../flutter-apps/utils/redfire_test

flutter:
  uses-material-design: true
