name: astro_dev_tools_screen
description: A widget for visualising state changes in an app using redux.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  astro:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/astro
  astro_widgets:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_widgets
  json_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_types

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.4
  astro_widgets_test_utils:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_widgets_test_utils
