name: astro_error_handling_interface
description: An interface for astro error handling plugins to implement.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  astro_state_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/interfaces/astro_state_interface

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
