name: get_google_api_credentials
description: A Dart CLI app to obtain credentials for accessing Google APIs.
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
