name: cloud_firestore_extensions
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cloud_firestore: ^3.2.0
  firestore_service_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/interfaces/firestore_service_interface
  json_utils:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_utils

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

