name: enspyr_redux
description: A simplified redux implementation with more constraints, such as each action has only one reducer/middleware.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
