name: redfire_test
description: Utilities to simplify testing in apps that use redfire.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core:
  firebase_auth:
  google_sign_in:
  sign_in_with_apple:
  http:
  redux:
  mockito:
  freezed_annotation:
  json_annotation: ^4.6.0
  fast_immutable_collections:

  redfire:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/redfire
  enspyr_lints:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/enspyr_lints  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:
  json_serializable: