// Mocks generated by Mockito 5.0.16 from annotations
// in redfire_test/src/test-doubles/auth/mocks/auth_test_doubles.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:google_sign_in/google_sign_in.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sign_in_with_apple/sign_in_with_apple.dart' as _i6;

import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart'
    as _i4;
import 'package:redfire/src/platform/plugins/wrappers/apple_signin_wrapper.dart'
    as _i7;
import 'package:sign_in_with_apple_platform_interface/sign_in_with_apple_platform_interface.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGoogleSignInAuthentication_0 extends _i1.Fake
    implements _i2.GoogleSignInAuthentication {}

class _FakeAuthorizationCredentialAppleID_1 extends _i1.Fake
    implements _i3.AuthorizationCredentialAppleID {}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i2.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SignInOption get signInOption =>
      (super.noSuchMethod(Invocation.getter(#signInOption),
          returnValue: _i4.SignInOption.standard) as _i4.SignInOption);
  @override
  List<String> get scopes =>
      (super.noSuchMethod(Invocation.getter(#scopes), returnValue: <String>[])
          as List<String>);
  @override
  _i5.Stream<_i2.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(Invocation.getter(#onCurrentUserChanged),
              returnValue: Stream<_i2.GoogleSignInAccount?>.empty())
          as _i5.Stream<_i2.GoogleSignInAccount?>);
  @override
  _i5.Future<_i2.GoogleSignInAccount?> signInSilently(
          {bool? suppressErrors = true, bool? reAuthenticate = false}) =>
      (super.noSuchMethod(
              Invocation.method(#signInSilently, [], {
                #suppressErrors: suppressErrors,
                #reAuthenticate: reAuthenticate
              }),
              returnValue: Future<_i2.GoogleSignInAccount?>.value())
          as _i5.Future<_i2.GoogleSignInAccount?>);
  @override
  _i5.Future<bool> isSignedIn() =>
      (super.noSuchMethod(Invocation.method(#isSignedIn, []),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i2.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(Invocation.method(#signIn, []),
              returnValue: Future<_i2.GoogleSignInAccount?>.value())
          as _i5.Future<_i2.GoogleSignInAccount?>);
  @override
  _i5.Future<_i2.GoogleSignInAccount?> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
              returnValue: Future<_i2.GoogleSignInAccount?>.value())
          as _i5.Future<_i2.GoogleSignInAccount?>);
  @override
  _i5.Future<_i2.GoogleSignInAccount?> disconnect() =>
      (super.noSuchMethod(Invocation.method(#disconnect, []),
              returnValue: Future<_i2.GoogleSignInAccount?>.value())
          as _i5.Future<_i2.GoogleSignInAccount?>);
  @override
  _i5.Future<bool> requestScopes(List<String>? scopes) =>
      (super.noSuchMethod(Invocation.method(#requestScopes, [scopes]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAccount extends _i1.Mock
    implements _i2.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(Invocation.getter(#email), returnValue: '')
          as String);
  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  _i5.Future<_i2.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(Invocation.getter(#authentication),
              returnValue: Future<_i2.GoogleSignInAuthentication>.value(
                  _FakeGoogleSignInAuthentication_0()))
          as _i5.Future<_i2.GoogleSignInAuthentication>);
  @override
  _i5.Future<Map<String, String>> get authHeaders => (super.noSuchMethod(
          Invocation.getter(#authHeaders),
          returnValue: Future<Map<String, String>>.value(<String, String>{}))
      as _i5.Future<Map<String, String>>);
  @override
  _i5.Future<void> clearAuthCache() =>
      (super.noSuchMethod(Invocation.method(#clearAuthCache, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SignInWithApple].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithApple extends _i1.Mock implements _i6.SignInWithApple {
  MockSignInWithApple() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
}

/// A class which mocks [SignInWithAppleWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithAppleWrapper extends _i1.Mock
    implements _i7.SignInWithAppleWrapper {
  MockSignInWithAppleWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.AuthorizationCredentialAppleID> getCredential(
          {List<_i3.AppleIDAuthorizationScopes>? scopes}) =>
      (super.noSuchMethod(
              Invocation.method(#getCredential, [], {#scopes: scopes}),
              returnValue: Future<_i3.AuthorizationCredentialAppleID>.value(
                  _FakeAuthorizationCredentialAppleID_1()))
          as _i5.Future<_i3.AuthorizationCredentialAppleID>);
  @override
  String toString() => super.toString();
}
