name: astro_state_interface
description: Immutable state for the astro package.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  json_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/json_types

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
