name: the_process
description: A tool to automate "the process", a system for organising collaboration.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # astro
  astro:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro
  astro_types:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_types
  astro_locator:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/utils/astro_locator
  astro_inspector_screen:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_inspector_screen
  astro_auth:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_auth
  astro_error_handling:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_error_handling
  astro_navigation:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/astro_navigation
  # firestore
  firestore_service_flutterfire:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/flutter/utils/flutterfire/firestore_service_flutterfire
  firestore_service_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/dart/interfaces/firestore_service_interface

  # utils 
  uuid: ^3.0.5
  http: ^0.13.4

dev_dependencies:
  # general testing
  flutter_test:
    sdk: flutter
  test: ^1.19.5
  mockito: ^5.0.17

flutter:
  uses-material-design: true # we use material icons for dropdowns etc.