name: the_process
description: A tool to automate "the process", a system for organising collaboration.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # redfire 
  redfire:
    path: ../../../../flutter/apps/utils/redfire
  firestore_service_interface:
    git:
      url: https://github.com/enspyrco/monorepo.git
      path: packages/interfaces/firestore_service_interface

  # redux
  redux:
  flutter_redux:
  
  # redux - app state
  freezed_annotation:
  json_annotation: ^4.6.0
  fast_immutable_collections: ^7.1.2

  # utils 
  uuid: ^3.0.5
  http: ^0.13.4

dev_dependencies:
  # general testing
  flutter_test:
    sdk: flutter
  test: ^1.19.5
  mockito: ^5.0.17
  
  # redfire
  redfire_lints:
    path: ../../../../flutter/apps/utils/redfire_lints
  redfire_test:
    path: ../../../../flutter/apps/utils/redfire_test
  
  # code gen
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true # we use material icons for dropdowns etc.