name: flutter_box2d_macos
description: A new flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_box2d_platform_interface:
    path: ../flutter_box2d_platform_interface
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^4.1.3

ffigen:
  name: 'Box2DBindings'
  description: 'Bindings for Box2D & Liquidfun'
  output: 'generated_bindings.dart'
  llvm-path:
    - '/opt/homebrew/opt/llvm'
  headers:
    entry-points:
      - 'macos/Classes/bindings/box2d_glue.h'
    include-directives:
      - 'macos/Classes/**/*.h'
  compiler-opts:
    - '-Imacos/Classes/include/box2d'
    - '-Wno-nullability-completeness'

flutter:
  plugin:
    implements: flutter_box2d
    platforms:
      macos:
        dartPluginClass: FlutterBox2DMacos
