// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// A shape is used for collision detection. You can create a shape however you like.
/// Shapes used for simulation in b2World are created automatically when a b2Fixture
/// is created. Shapes may encapsulate a one or more child shapes.
abstract class b2ShapeType {
  static const int e_circle = 0;
  static const int e_edge = 1;
  static const int e_polygon = 2;
  static const int e_chain = 3;
  static const int e_typeCount = 4;
}
