name: tests

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1

    # Install Java, needed by flutter-action.
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Install Flutter.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    
    # Get project dependencies.
    - run: flutter pub get

    # Generate missing files.
    - run: flutter pub run build_runner build
    
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .

    # Statically analyze the Dart code for any errors.
    # - run: dart analyze .
    
    # Run tests.
    - run: flutter test --no-sound-null-safety
