name: fns-tests

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  run-tests:
    name: Cloud Functions Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions

    steps:
    # Check out the current branch.
    - uses: actions/checkout@v2
    # Install Node.
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        # Use the latest Node 12 version
        node-version: 12.x
    
    ##############################################
    # setup-gcloud & download credential files 
    ##############################################
    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: the-process-tool
        service_account_key: ${{ secrets.CREDENTIALS_SERVICE_ACCOUNT_KEY }}
    - name: Download credential files
      run: gsutil cp gs://the-process-tool-credentials/project_credentials.json src/project_credentials.json

    - run: npm install -g typescript
    - run: npm install -g ts-node
    - run: npm install -g ts-mocha
    - run: npm install -g mocha
 
    # install dependencies using clean install to avoid package lock updates
    - run: npm ci
    # build the project if necessary
    - run: npm run build --if-present
    # finally run the tests
    - run: npm test
