name: Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: adventure_maker
            package_name: "adventure_maker"
          - package: flireator
            package_name: "flireator"
          - package: redfire
            package_name: "redfire"
          - package: redfire_test
            package_name: "redfire_test"
          - package: tech_world
            package_name: "tech_world"
          - package: the_process
            package_name: "the_process"
          - package: ws_game_server
            package_name: "ws_game_server"
          - package: ws_game_server_types
            package_name: "ws_game_server_types"
    steps:
      - uses: actions/checkout@v2
      - uses: enspyrco/run-tests-action@v0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          