name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Flutter image
        uses: docker/build-push-action@v2
        with:
          context: ./flutter_container
          push: true
          tags: enspyrco/ci_tools_flutter:2.8.1
      
      - name: Build and push Dart image
        uses: docker/build-push-action@v2
        with:
          context: ./dart_container
          push: true
          tags: enspyrco/ci_tools_dart:2.15.1