name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  setup_matrix:
    name: Setup Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix_json: ${{ steps.read-matrix.outputs.json }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: .github/scripts/identify_affected_packages
      - id: read-matrix
        run: |
          content=`jq -c . .github/matrix.json`
          echo "json=$content" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.read-matrix.outputs.json }}
  
  run_tests:
    # if: needs.setup_matrix.outputs.matrix_json.include[0] != null # only run if matrix is non-empty
    name: Run Tests
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ${{ fromJson(needs.setup_matrix.outputs.matrix_json) }}
    
    # container: enspyrco/ci-tools:stable
    defaults:
      run:
        working-directory: ./packages/${{ matrix.path }}
    
    steps:
      - uses: actions/checkout@v3

      - run: echo needs.setup_matrix.outputs.matrix_json

      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: ~/_flutter
          key: ${{ runner.os }}-${{ matrix.package }}-${{ hashFiles('.github/flutter_stable_version.txt') }}

      - name: Install Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        run: |
          cd $HOME
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
          cd $GITHUB_WORKSPACE
      
      - name: Put flutter on the path
        run: echo "$HOME/_flutter/bin" >> $GITHUB_PATH

      - run: flutter pub get

      - name: Run build_runner if required
        if: ${{ matrix.source_gen }}
        run: flutter pub run build_runner build
      
      - run: flutter test
