name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: read_matrix
        run: |
          content=$(cat .github/matrix.json)
          echo "json=${content//'%'/'%25'}" >> $GITHUB_OUTPUT

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ${{fromJson(needs.read_matrix.outputs.json)}}
    
    # container: enspyrco/ci-tools:stable
    defaults:
      run:
        working-directory: ./packages/${{ matrix.package }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: ~/_flutter
          key: ${{ runner.os }}-${{ matrix.package_name }}-${{ hashFiles('.github/flutter_stable_version.txt') }}

      - name: Install Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        run: |
          cd $HOME
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
          cd $GITHUB_WORKSPACE
      
      - name: Put flutter on the path
        run: echo "$HOME/_flutter/bin" >> $GITHUB_PATH

      - run: flutter pub get

      - name: Run build_runner if required
        if: ${{ matrix.run_code_gen }}
        run: flutter pub run build_runner build
      
      - run: flutter test
